version: "3.8"
services:
  postgresql:
    build: ./docker/postgresql
    networks:
      - database
    init: true
    volumes:
      - "/var/lib/postgresql/data"
      - "pgsock:/var/run/postgresql"

  service:
    build: ./docker/service
    init: true
    networks:
      - database
    ports:
      - "15432:15432"

  socat:
    image: alpine/socat
    networks:
      - database
    init: true
    ports:
      - "5432:5432"
    command: "tcp-listen:5432,fork,reuseaddr unix-connect:/var/run/postgresql/.s.PGSQL.5432"
    volumes:
      - "pgsock:/var/run/postgresql"

volumes:
  pgsock: {}

networks:
  database: {}